;This file is just the reference to know all env, and heritance between them
[production]

resources.view.scriptPath[] = APPLICATION_PATH "/modules/history/views/scripts"

[pre-prod : production]

[testing : production]

[staging : production]

[development : production]

[local : production]
